
pod 'JSONKit'
pod 'ASIHTTPRequest'
pod "AFNetworking", "~> 2.0"
pod 'EGOTableViewPullRefresh', '~> 0.1.0'
pod 'MMDrawerController', '~> 0.5.5'


pod 'UMengFeedback', '~> 1.4.1'

pod 'UMeng', '~> 2.2.1'


